version: '3.8'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: online-store

volumes:
  mongo-data:
